import type { Metadata } from 'next';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box } from '@mui/material/index';
import ThemeRegistry from 'ThemeRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <Box component="body" sx={{ display: 'flex', height: '100vh' }}>
        <AppRouterCacheProvider>
          <ThemeRegistry options={{ key: 'mui-theme' }}>
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                display: 'flex',
              }}
            >
              {children}
            </Box>
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </Box>
    </html>
  );
};

export default RootLayout;
